tags: /tags
categories: /categories

background: http://aynup.com/api/public/img/1575718373609469bba0a564235dfceede42db14f17b0.jpeg

self_proverbs: 恐惧决定你的边界，痛苦带给你能量，愉悦会指引你的方向
self_info: 废柴大学生一枚，前端菜鸟。现居杭州，大一的时候意外接触到了前端，从此对互联网的世界产生了浓厚的兴趣。现在主要在学校里自学网页开发，未来希望能在大四之前开发一套自己的WEB和APP框架。
self_address_cn: 杭州
self_address_en: HangZhou
self_address_network: http://aynup.com


sidebar:
  title: 遗忘之所
  title_image: http://aynup.com/api/public/img/15757302638522adf91272182d75fa1eff6a226306eb9.jpg
  content: 废柴大学生一枚，前端菜鸟。现居杭州，大一的时候意外接触到了前端，从此对互联网的世界产生了浓厚的兴趣。现在主要在学校里自学网页开发，未来希望能在大四之前开发一套自己的WEB和APP框架。
